// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: statether/statether/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSaveEthaddressState struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EthAddress      string `protobuf:"bytes,2,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	Block           uint64 `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	Nonce           uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	StoragePosition uint64 `protobuf:"varint,5,opt,name=storagePosition,proto3" json:"storagePosition,omitempty"`
}

func (m *MsgSaveEthaddressState) Reset()         { *m = MsgSaveEthaddressState{} }
func (m *MsgSaveEthaddressState) String() string { return proto.CompactTextString(m) }
func (*MsgSaveEthaddressState) ProtoMessage()    {}
func (*MsgSaveEthaddressState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3454f3c906df7237, []int{0}
}
func (m *MsgSaveEthaddressState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSaveEthaddressState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSaveEthaddressState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSaveEthaddressState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSaveEthaddressState.Merge(m, src)
}
func (m *MsgSaveEthaddressState) XXX_Size() int {
	return m.Size()
}
func (m *MsgSaveEthaddressState) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSaveEthaddressState.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSaveEthaddressState proto.InternalMessageInfo

func (m *MsgSaveEthaddressState) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSaveEthaddressState) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *MsgSaveEthaddressState) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *MsgSaveEthaddressState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgSaveEthaddressState) GetStoragePosition() uint64 {
	if m != nil {
		return m.StoragePosition
	}
	return 0
}

type MsgSaveEthaddressStateResponse struct {
	EthAddress string `protobuf:"bytes,1,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
}

func (m *MsgSaveEthaddressStateResponse) Reset()         { *m = MsgSaveEthaddressStateResponse{} }
func (m *MsgSaveEthaddressStateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSaveEthaddressStateResponse) ProtoMessage()    {}
func (*MsgSaveEthaddressStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3454f3c906df7237, []int{1}
}
func (m *MsgSaveEthaddressStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSaveEthaddressStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSaveEthaddressStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSaveEthaddressStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSaveEthaddressStateResponse.Merge(m, src)
}
func (m *MsgSaveEthaddressStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSaveEthaddressStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSaveEthaddressStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSaveEthaddressStateResponse proto.InternalMessageInfo

func (m *MsgSaveEthaddressStateResponse) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

type MsgGetEthaddressState struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EthAddress      string `protobuf:"bytes,2,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	Block           uint64 `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	Nonce           uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	StoragePosition uint64 `protobuf:"varint,5,opt,name=storagePosition,proto3" json:"storagePosition,omitempty"`
}

func (m *MsgGetEthaddressState) Reset()         { *m = MsgGetEthaddressState{} }
func (m *MsgGetEthaddressState) String() string { return proto.CompactTextString(m) }
func (*MsgGetEthaddressState) ProtoMessage()    {}
func (*MsgGetEthaddressState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3454f3c906df7237, []int{2}
}
func (m *MsgGetEthaddressState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGetEthaddressState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGetEthaddressState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGetEthaddressState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetEthaddressState.Merge(m, src)
}
func (m *MsgGetEthaddressState) XXX_Size() int {
	return m.Size()
}
func (m *MsgGetEthaddressState) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetEthaddressState.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetEthaddressState proto.InternalMessageInfo

func (m *MsgGetEthaddressState) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgGetEthaddressState) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *MsgGetEthaddressState) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *MsgGetEthaddressState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgGetEthaddressState) GetStoragePosition() uint64 {
	if m != nil {
		return m.StoragePosition
	}
	return 0
}

type MsgGetEthaddressStateResponse struct {
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *MsgGetEthaddressStateResponse) Reset()         { *m = MsgGetEthaddressStateResponse{} }
func (m *MsgGetEthaddressStateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgGetEthaddressStateResponse) ProtoMessage()    {}
func (*MsgGetEthaddressStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3454f3c906df7237, []int{3}
}
func (m *MsgGetEthaddressStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGetEthaddressStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGetEthaddressStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGetEthaddressStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetEthaddressStateResponse.Merge(m, src)
}
func (m *MsgGetEthaddressStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgGetEthaddressStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetEthaddressStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetEthaddressStateResponse proto.InternalMessageInfo

func (m *MsgGetEthaddressStateResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*MsgSaveEthaddressState)(nil), "statether.statether.MsgSaveEthaddressState")
	proto.RegisterType((*MsgSaveEthaddressStateResponse)(nil), "statether.statether.MsgSaveEthaddressStateResponse")
	proto.RegisterType((*MsgGetEthaddressState)(nil), "statether.statether.MsgGetEthaddressState")
	proto.RegisterType((*MsgGetEthaddressStateResponse)(nil), "statether.statether.MsgGetEthaddressStateResponse")
}

func init() { proto.RegisterFile("statether/statether/tx.proto", fileDescriptor_3454f3c906df7237) }

var fileDescriptor_3454f3c906df7237 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0x4a, 0x23, 0x41,
	0x10, 0x4e, 0x6f, 0x7e, 0x76, 0xb7, 0x2e, 0x0b, 0x9d, 0x35, 0x0c, 0x41, 0x9b, 0x90, 0x53, 0x50,
	0x98, 0x60, 0x82, 0x78, 0x55, 0x41, 0x3c, 0x05, 0x65, 0x72, 0xf3, 0x36, 0x99, 0x14, 0x33, 0x83,
	0xb1, 0x3b, 0x74, 0x95, 0x1a, 0xdf, 0xc2, 0xb7, 0xd0, 0x47, 0xf1, 0x98, 0xa3, 0x47, 0x49, 0x5e,
	0xc1, 0x07, 0x90, 0xcc, 0x98, 0x31, 0xc4, 0x11, 0xf4, 0xe6, 0xad, 0xbe, 0xaf, 0x3e, 0xba, 0xbf,
	0xaa, 0xee, 0x0f, 0x36, 0x89, 0x7d, 0x46, 0x8e, 0xd0, 0xb6, 0xdf, 0x2b, 0x9e, 0xb8, 0x63, 0x6b,
	0xd8, 0xc8, 0x6a, 0xc6, 0xb9, 0x59, 0xd5, 0x7c, 0x10, 0x50, 0xeb, 0x51, 0xd8, 0xf7, 0xaf, 0xf1,
	0x98, 0x23, 0x7f, 0x38, 0xb4, 0x48, 0xd4, 0x5f, 0xb4, 0xa5, 0x03, 0xbf, 0x03, 0x8b, 0x3e, 0x1b,
	0xeb, 0x88, 0x86, 0x68, 0xfd, 0xf5, 0x96, 0x50, 0x2a, 0x00, 0xe4, 0xe8, 0x30, 0x15, 0x3b, 0xbf,
	0x92, 0xe6, 0x0a, 0x23, 0xff, 0x43, 0x79, 0x30, 0x32, 0xc1, 0x85, 0x53, 0x6c, 0x88, 0x56, 0xc9,
	0x4b, 0xc1, 0x82, 0xd5, 0x46, 0x07, 0xe8, 0x94, 0x52, 0x36, 0x01, 0xb2, 0x05, 0xff, 0x88, 0x8d,
	0xf5, 0x43, 0x3c, 0x33, 0x14, 0x73, 0x6c, 0xb4, 0x53, 0x4e, 0xfa, 0xeb, 0x74, 0xf3, 0x00, 0x54,
	0xbe, 0x53, 0x0f, 0x69, 0x6c, 0x34, 0xe1, 0x9a, 0x2f, 0xb1, 0xee, 0xab, 0x79, 0x2f, 0x60, 0xa3,
	0x47, 0xe1, 0x09, 0xf2, 0x4f, 0x9f, 0x75, 0x1f, 0xb6, 0x72, 0x8d, 0x66, 0xa3, 0xd6, 0xa0, 0x82,
	0x93, 0x98, 0x38, 0x1d, 0xf3, 0x8f, 0xf7, 0x86, 0x3a, 0x2f, 0x02, 0x8a, 0x3d, 0x0a, 0xe5, 0x0d,
	0x54, 0xf3, 0xde, 0x74, 0xc7, 0xcd, 0xf9, 0x04, 0x6e, 0xfe, 0x5a, 0xeb, 0xdd, 0x6f, 0x88, 0x33,
	0x63, 0x0c, 0x32, 0x67, 0xbf, 0xdb, 0x9f, 0x1d, 0xf5, 0x51, 0x5b, 0xef, 0x7c, 0x5d, 0xbb, 0xbc,
	0xf5, 0xe8, 0xf4, 0x71, 0xa6, 0xc4, 0x74, 0xa6, 0xc4, 0xf3, 0x4c, 0x89, 0xbb, 0xb9, 0x2a, 0x4c,
	0xe7, 0xaa, 0xf0, 0x34, 0x57, 0x85, 0xf3, 0xbd, 0x30, 0xe6, 0xe8, 0x6a, 0xe0, 0x06, 0xe6, 0xb2,
	0xad, 0x71, 0x44, 0x46, 0x13, 0xdb, 0xb6, 0xe9, 0xea, 0xdd, 0x95, 0x8c, 0x4c, 0x56, 0xf3, 0x72,
	0x3b, 0x46, 0x1a, 0x54, 0x92, 0xcc, 0x74, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x5c, 0x19,
	0x12, 0x53, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SaveEthaddressState(ctx context.Context, in *MsgSaveEthaddressState, opts ...grpc.CallOption) (*MsgSaveEthaddressStateResponse, error)
	GetEthaddressState(ctx context.Context, in *MsgGetEthaddressState, opts ...grpc.CallOption) (*MsgGetEthaddressStateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SaveEthaddressState(ctx context.Context, in *MsgSaveEthaddressState, opts ...grpc.CallOption) (*MsgSaveEthaddressStateResponse, error) {
	out := new(MsgSaveEthaddressStateResponse)
	err := c.cc.Invoke(ctx, "/statether.statether.Msg/SaveEthaddressState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetEthaddressState(ctx context.Context, in *MsgGetEthaddressState, opts ...grpc.CallOption) (*MsgGetEthaddressStateResponse, error) {
	out := new(MsgGetEthaddressStateResponse)
	err := c.cc.Invoke(ctx, "/statether.statether.Msg/GetEthaddressState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SaveEthaddressState(context.Context, *MsgSaveEthaddressState) (*MsgSaveEthaddressStateResponse, error)
	GetEthaddressState(context.Context, *MsgGetEthaddressState) (*MsgGetEthaddressStateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SaveEthaddressState(ctx context.Context, req *MsgSaveEthaddressState) (*MsgSaveEthaddressStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveEthaddressState not implemented")
}
func (*UnimplementedMsgServer) GetEthaddressState(ctx context.Context, req *MsgGetEthaddressState) (*MsgGetEthaddressStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEthaddressState not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SaveEthaddressState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSaveEthaddressState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SaveEthaddressState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statether.statether.Msg/SaveEthaddressState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SaveEthaddressState(ctx, req.(*MsgSaveEthaddressState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetEthaddressState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetEthaddressState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetEthaddressState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statether.statether.Msg/GetEthaddressState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetEthaddressState(ctx, req.(*MsgGetEthaddressState))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "statether.statether.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveEthaddressState",
			Handler:    _Msg_SaveEthaddressState_Handler,
		},
		{
			MethodName: "GetEthaddressState",
			Handler:    _Msg_GetEthaddressState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statether/statether/tx.proto",
}

func (m *MsgSaveEthaddressState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSaveEthaddressState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSaveEthaddressState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StoragePosition != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StoragePosition))
		i--
		dAtA[i] = 0x28
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x20
	}
	if m.Block != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSaveEthaddressStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSaveEthaddressStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSaveEthaddressStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGetEthaddressState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGetEthaddressState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGetEthaddressState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StoragePosition != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StoragePosition))
		i--
		dAtA[i] = 0x28
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x20
	}
	if m.Block != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGetEthaddressStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGetEthaddressStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGetEthaddressStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSaveEthaddressState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Block != 0 {
		n += 1 + sovTx(uint64(m.Block))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	if m.StoragePosition != 0 {
		n += 1 + sovTx(uint64(m.StoragePosition))
	}
	return n
}

func (m *MsgSaveEthaddressStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgGetEthaddressState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Block != 0 {
		n += 1 + sovTx(uint64(m.Block))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	if m.StoragePosition != 0 {
		n += 1 + sovTx(uint64(m.StoragePosition))
	}
	return n
}

func (m *MsgGetEthaddressStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Exists {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSaveEthaddressState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSaveEthaddressState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSaveEthaddressState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePosition", wireType)
			}
			m.StoragePosition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoragePosition |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSaveEthaddressStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSaveEthaddressStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSaveEthaddressStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGetEthaddressState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGetEthaddressState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGetEthaddressState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePosition", wireType)
			}
			m.StoragePosition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoragePosition |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGetEthaddressStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGetEthaddressStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGetEthaddressStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
