version: 1
accounts:
- name: alice
  mnemonic: discover twice deer deputy table wheat since this breeze opera mind educate approve strategy dress stem find enjoy beef net barely waste gate infant
  coins:
  - 20000token
  - 200000000stake
- name: bob
  mnemonic: remain expose upon swift donate maximum adult orchard rapid seven west toward wage holiday game build piano merge luggage gospel ancient fun melody void
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
