// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgDisableEthAddress } from "./types/etherstate/etherstate/tx";
import { MsgEnableEthAddress } from "./types/etherstate/etherstate/tx";

import { EthereumAddress as typeEthereumAddress} from "./types"
import { Params as typeParams} from "./types"

export { MsgDisableEthAddress, MsgEnableEthAddress };

type sendMsgDisableEthAddressParams = {
  value: MsgDisableEthAddress,
  fee?: StdFee,
  memo?: string
};

type sendMsgEnableEthAddressParams = {
  value: MsgEnableEthAddress,
  fee?: StdFee,
  memo?: string
};


type msgDisableEthAddressParams = {
  value: MsgDisableEthAddress,
};

type msgEnableEthAddressParams = {
  value: MsgEnableEthAddress,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgDisableEthAddress({ value, fee, memo }: sendMsgDisableEthAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDisableEthAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDisableEthAddress({ value: MsgDisableEthAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDisableEthAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgEnableEthAddress({ value, fee, memo }: sendMsgEnableEthAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgEnableEthAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgEnableEthAddress({ value: MsgEnableEthAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgEnableEthAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgDisableEthAddress({ value }: msgDisableEthAddressParams): EncodeObject {
			try {
				return { typeUrl: "/etherstate.etherstate.MsgDisableEthAddress", value: MsgDisableEthAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDisableEthAddress: Could not create message: ' + e.message)
			}
		},
		
		msgEnableEthAddress({ value }: msgEnableEthAddressParams): EncodeObject {
			try {
				return { typeUrl: "/etherstate.etherstate.MsgEnableEthAddress", value: MsgEnableEthAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgEnableEthAddress: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						EthereumAddress: getStructure(typeEthereumAddress.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			EtherstateEtherstate: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;